services:
  sing-box:
    container_name: sing-box
    image: itdoginfo/sing-box:v1.9.3
    ports:
      - "443:443"
    environment:
      PROTOCOL: shadowsocks
      PASS: "pass"
      SERVER: domain\ip
      USERS: "User1;User2;User5;User3;"
      #PUBLIC_KEY:
    restart: always
    # Enable for custom config (multiple accounts for example)
    # volumes:
    #  - ./config:/etc/sing-box/
