services:
  spbstikaserver:
    container_name: spbstikaserver
    image: spbstika/spbstikaserver
    ports:
      - "443:443"
    environment:
      PROTOCOL: shadowsocks
      PASS: "pass"
      SERVER: sss.com
      USERS: ["User1","User2","User5","User3"]
      #PUBLIC_KEY:
    restart: always
    # Enable for custom config (multiple accounts for example)
    # volumes:
    #  - ./config:/etc/sing-box/
